version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5434:5432
    env_file: 
      - backend/.env
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    networks:
      - ping-pong
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - ping-pong
    depends_on: 
      - database

networks:
  ping-pong:
    driver: bridge
